# Generated by Django 2.1.1 on 2018-09-24 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_monastic', models.BooleanField()),
                ('monastic_name', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
